- hosts: all
  become: yes
  tasks:
    - name: Install nginx
      yum: name=nginx
           state=present
    - name: Start nginx on boot
      service: name=nginx
               enabled=yes
               state=started

    - name: Install Nessus Agent
      yum: name=https://s3.amazonaws.com/bluebeam.deploy/Nessus/NessusAgent-7.0.3-es7.x86_64.rpm
           state=present

    - name: Add this command to rc.local
      command: echo "/opt/nessus_agent/sbin/nessuscli agent link --key=9eb83491b27fb51c9b1145d42d59f02b08a49fca670816d950dc8f8cc75639c2 --host=cloud.tenable.com --port=443" >> /etc/rc.d/rc.local

    - name: Start nessus Agent after linking
      command: echo "/bin/systemctl start nessusagent.service" >> /etc/rc.d/rc.local
    
    - name: Ensure that rc.local is executable
      file: path=/etc/rc.d/rc.local
            mode=0755
            owner=root
            group=root
 
